### ISSUE TITLE
v2 Release

### ISSUE THREAD

**Issue by ebebbington** [drashland/deno-drash-realworld-example-app#96]
- [ ] tests: Write advanced tests (#94)
- [ ] docs: Expand upon Bult With Section (#92)
- [ ] fix: Header item disppears on refresh (#90)
- [ ] feat: Don't allow duplicate articles (#74)
- [ ] docs: Move to tsdoc (#68)
- [ ] ci: add update workflow (#66)
- [ ] tests: add stress testing (#49)
- [ ] fix: Cors issue for Apache (#46)
- [ ] feat: Sanitise input (#40)
- [ ] JWT (is this needed?) (#28)
